version: '3'
services:
  terramind-backend:
    user: node
    container_name: terramind-backend
    build: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 9229:9229
      - 8081:3000
    depends_on:
      - terramind-postgres
    command: npm run start:debug

  terramind-postgres:
    container_name: terramind-postgres
    image: postgres:14-alpine
    environment:
      PG_DATA: /var/lib/postgresql/data
    env_file:
      - ./backend/docker.env
    ports:
      - 5432:5432
    volumes:
      - pgdata-terramind:/var/lib/postgresql/data

  terramind-frontend:
    depends_on:
      - terramind-backend
    build: ./frontend
    ports:
      - '5000:5000'
    container_name: terramin-frontend

networks:
  postgres:
    driver: bridge
volumes:
  pgdata-terramind:
